baseurl: ''
url: ''
heading: Digital Garden
copyright:
  year: 2021
  msg: Your Name
preferences:
  search:
    enabled: true
    shortcut_hint:
      enabled: true
  wiki_style_link:
    enabled: true
  sidenotes:
    enabled: true
  transclusion:
    enabled: true
  image:
    enabled: true
  pagepreview:
    enabled: true
  highlighting:
    enabled: true
    color: DAEDFF
  backlinks:
    enabled: true
  related:
    enabled: false
  wrapping:
    enabled: true
  contextmenu:
    enabled: false
    copylink:
      enabled: false
    newtab:
      enabled: false
    backlinks:
      enabled: false
    related:
      enabled: false
  flashcards:
    enabled: false
  homepage:
    enabled: true
encoding: utf-8
theme: null
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-tidy
collections:
  notes:
    output: true
    permalink: '/notes/:title'
disqus:
  shortname: null
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: katex
  smart_quotes:
    - apos
    - apos
    - quot
    - quot
  syntax_highlighter: rouge
sass:
  style: compressed
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: Post
      permalink: '/posts/:title'
      content-type: post
  - scope:
      path: ''
      type: notes
    values:
      layout: Post
      content-type: notes
